const {i18n} = require('./next-i18next.config')

const nextConfig = {
  i18n,
  reactStrictMode: true,
  swcMinify: true,
  trailingSlash: true,

  async redirects() {
    return [
      {source: '/de/about-us/', destination: '/about-us/', locale: false, permanent: true},
      {source: '/es/about-us/', destination: '/about-us/', locale: false, permanent: true},
      {source: '/fr/about-us/', destination: '/about-us/', locale: false, permanent: true},
      {source: '/hi/about-us/', destination: '/about-us/', locale: false, permanent: true},
      {source: '/id/about-us/', destination: '/about-us/', locale: false, permanent: true},
      {source: '/it/about-us/', destination: '/about-us/', locale: false, permanent: true},
      {source: '/ja/about-us/', destination: '/about-us/', locale: false, permanent: true},
      {source: '/ko/about-us/', destination: '/about-us/', locale: false, permanent: true},
      {source: '/my/about-us/', destination: '/about-us/', locale: false, permanent: true},
      {source: '/ms/about-us/', destination: '/about-us/', locale: false, permanent: true},
      {source: '/ph/about-us/', destination: '/about-us/', locale: false, permanent: true},
      {source: '/pt/about-us/', destination: '/about-us/', locale: false, permanent: true},
      {source: '/ru/about-us/', destination: '/about-us/', locale: false, permanent: true},
      {source: '/th/about-us/', destination: '/about-us/', locale: false, permanent: true},
      {source: '/tr/about-us/', destination: '/about-us/', locale: false, permanent: true},
      {source: '/vi/about-us/', destination: '/about-us/', locale: false, permanent: true},
      {source: '/zh-cn/about-us/', destination: '/about-us/', locale: false, permanent: true},
      {source: '/zh-tw/about-us/', destination: '/about-us/', locale: false, permanent: true},
      {source: '/ar/about-us/', destination: '/about-us/', locale: false, permanent: true},
      {source: '/bn/about-us/', destination: '/about-us/', locale: false, permanent: true},
      {source: '/de/contact/', destination: '/contact/', locale: false, permanent: true},
      {source: '/es/contact/', destination: '/contact/', locale: false, permanent: true},
      {source: '/fr/contact/', destination: '/contact/', locale: false, permanent: true},
      {source: '/hi/contact/', destination: '/contact/', locale: false, permanent: true},
      {source: '/id/contact/', destination: '/contact/', locale: false, permanent: true},
      {source: '/it/contact/', destination: '/contact/', locale: false, permanent: true},
      {source: '/ja/contact/', destination: '/contact/', locale: false, permanent: true},
      {source: '/ko/contact/', destination: '/contact/', locale: false, permanent: true},
      {source: '/my/contact/', destination: '/contact/', locale: false, permanent: true},
      {source: '/ms/contact/', destination: '/contact/', locale: false, permanent: true},
      {source: '/ph/contact/', destination: '/contact/', locale: false, permanent: true},
      {source: '/pt/contact/', destination: '/contact/', locale: false, permanent: true},
      {source: '/ru/contact/', destination: '/contact/', locale: false, permanent: true},
      {source: '/th/contact/', destination: '/contact/', locale: false, permanent: true},
      {source: '/tr/contact/', destination: '/contact/', locale: false, permanent: true},
      {source: '/vi/contact/', destination: '/contact/', locale: false, permanent: true},
      {source: '/zh-cn/contact/', destination: '/contact/', locale: false, permanent: true},
      {source: '/zh-tw/contact/', destination: '/contact/', locale: false, permanent: true},
      {source: '/ar/contact/', destination: '/contact/', locale: false, permanent: true},
      {source: '/bn/contact/', destination: '/contact/', locale: false, permanent: true},
      {source: '/de/terms-condition/', destination: '/terms-condition/', locale: false, permanent: true},
      {source: '/es/terms-condition/', destination: '/terms-condition/', locale: false, permanent: true},
      {source: '/fr/terms-condition/', destination: '/terms-condition/', locale: false, permanent: true},
      {source: '/hi/terms-condition/', destination: '/terms-condition/', locale: false, permanent: true},
      {source: '/id/terms-condition/', destination: '/terms-condition/', locale: false, permanent: true},
      {source: '/it/terms-condition/', destination: '/terms-condition/', locale: false, permanent: true},
      {source: '/ja/terms-condition/', destination: '/terms-condition/', locale: false, permanent: true},
      {source: '/ko/terms-condition/', destination: '/terms-condition/', locale: false, permanent: true},
      {source: '/my/terms-condition/', destination: '/terms-condition/', locale: false, permanent: true},
      {source: '/ms/terms-condition/', destination: '/terms-condition/', locale: false, permanent: true},
      {source: '/ph/terms-condition/', destination: '/terms-condition/', locale: false, permanent: true},
      {source: '/pt/terms-condition/', destination: '/terms-condition/', locale: false, permanent: true},
      {source: '/ru/terms-condition/', destination: '/terms-condition/', locale: false, permanent: true},
      {source: '/th/terms-condition/', destination: '/terms-condition/', locale: false, permanent: true},
      {source: '/tr/terms-condition/', destination: '/terms-condition/', locale: false, permanent: true},
      {source: '/vi/terms-condition/', destination: '/terms-condition/', locale: false, permanent: true},
      {source: '/zh-cn/terms-condition/', destination: '/terms-condition/', locale: false, permanent: true},
      {source: '/zh-tw/terms-condition/', destination: '/terms-condition/', locale: false, permanent: true},
      {source: '/ar/terms-condition/', destination: '/terms-condition/', locale: false, permanent: true},
      {source: '/bn/terms-condition/', destination: '/terms-condition/', locale: false, permanent: true},
      {source: '/de/privacy-policy/', destination: '/privacy-policy/', locale: false, permanent: true},
      {source: '/es/privacy-policy/', destination: '/privacy-policy/', locale: false, permanent: true},
      {source: '/fr/privacy-policy/', destination: '/privacy-policy/', locale: false, permanent: true},
      {source: '/hi/privacy-policy/', destination: '/privacy-policy/', locale: false, permanent: true},
      {source: '/id/privacy-policy/', destination: '/privacy-policy/', locale: false, permanent: true},
      {source: '/it/privacy-policy/', destination: '/privacy-policy/', locale: false, permanent: true},
      {source: '/ja/privacy-policy/', destination: '/privacy-policy/', locale: false, permanent: true},
      {source: '/ko/privacy-policy/', destination: '/privacy-policy/', locale: false, permanent: true},
      {source: '/my/privacy-policy/', destination: '/privacy-policy/', locale: false, permanent: true},
      {source: '/ms/privacy-policy/', destination: '/privacy-policy/', locale: false, permanent: true},
      {source: '/ph/privacy-policy/', destination: '/privacy-policy/', locale: false, permanent: true},
      {source: '/pt/privacy-policy/', destination: '/privacy-policy/', locale: false, permanent: true},
      {source: '/ru/privacy-policy/', destination: '/privacy-policy/', locale: false, permanent: true},
      {source: '/th/privacy-policy/', destination: '/privacy-policy/', locale: false, permanent: true},
      {source: '/tr/privacy-policy/', destination: '/privacy-policy/', locale: false, permanent: true},
      {source: '/vi/privacy-policy/', destination: '/privacy-policy/', locale: false, permanent: true},
      {source: '/zh-cn/privacy-policy/', destination: '/privacy-policy/', locale: false, permanent: true},
      {source: '/zh-tw/privacy-policy/', destination: '/privacy-policy/', locale: false, permanent: true},
      {source: '/ar/privacy-policy/', destination: '/privacy-policy/', locale: false, permanent: true},
      {source: '/bn/privacy-policy/', destination: '/privacy-policy/', locale: false, permanent: true}
    ]
  }
};

const withPWA = require('next-pwa')({
  dest: 'public',
  register: true
});

module.exports = withPWA(nextConfig);
